fields:
  name:
    validate:
      type: 'string'
      maxCharLength: 50
      minCharLength: 3
      required: true
      ascii: true
    sanitize:
      escape: ''
      blacklist: ''
      trim: ' '
  dataname:
    validate:
      type: 'string'
      maxCharLength: 50
      minCharLength: 3
      required: true
      ascii: true
      alphanumeric: true
    sanitize:
      escape: ''
      blacklist: ''
      trim: ' '
  default_host_path:
    validate:
      type: 'string'
      minCharLength: 3
      required: true
      ascii: true
      fqdnInside: true
      startWith:
        - 'https://'
        - 'http://'
    sanitize:
      trim: ' '
      rtrim: '/'        
  default_username:
    validate:
      type: 'string'
      maxCharLength: 50
      minCharLength: 1
    sanitize:
      trim: ' '        
  default_password:
    validate:
      type: 'string'
      maxCharLength: 50
      minCharLength: 1
    sanitize:
      trim: ' '        
  breakpoint_width:
    validate:
      type: 'object'
  breakpoint_height:
    validate:
      type: 'object'
  capability:
    validate:
      type: 'object'
